version: '3'
services:
  ubuntu:
    build: ./docker_image/
    image: amplab_musicology:1.0
    stdin_open: true
    tty: true
    volumes:
      - .:/data
    ports:
      - "8080:8080"
#    command: jupyter lab --port=8080 --ip=0.0.0.0 --allow-root